site_name: 石家庄二中 Wiki
site_url: https://sjzezwiki.github.io/sjzezwiki
repo_url: https://github.com/sjzezwiki/sjzezwiki
copyright: SJZEZ
pages:
- "简介": 'index.md'
- "概况":
    - "北校区(本部)": 'gk/north.md'
    - "南校区": 'gk/south.md'
    - "润德校区": 'gk/runde.md'
    - "西校区": 'gk/west.md'
    - "石门校区": 'gk/shimen.md'
- "招生":
    - "综述": 'zs/gen.md'
    - "北校区(本部)": 'zs/north.md'
    - "南校区": 'zs/south.md'
    - "润德校区": 'zs/runde.md'
    - "西校区": 'zs/west.md'
    - "石门校区": 'zs/shimen.md'
    - "初中": 'zs/junior.md'